In [35]:
import pandas as pd
from matplotlib import pyplot as plt
import matplotlib
import numpy as np

In [36]:
combined = pd.read_csv("../data/combined.csv")

In [37]:
combined.head()

,PassengerId,Sex,Age,SibSp,Parch,Fare,Title_Master,Title_Miss,Title_Mr,Title_Mrs,...,Ticket_STONO2,Ticket_STONOQ,Ticket_SWPP,Ticket_WC,Ticket_WEP,Ticket_XXX,FamilySize,Singleton,SmallFamily,LargeFamily
0,1,1,22.0,1,0,7.2500,0,0,1,0,...,0,0,0,0,0,0,2,0,1,0
1,2,0,38.0,1,0,71.2833,0,0,0,1,...,0,0,0,0,0,0,2,0,1,0
2,3,0,26.0,0,0,7.9250,0,1,0,0,...,1,0,0,0,0,0,1,1,0,0
3,4,0,35.0,1,0,53.1000,0,0,0,1,...,0,0,0,0,0,1,2,0,1,0
4,5,1,35.0,0,0,8.0500,0,0,1,0,...,0,0,0,0,0,1,1,1,0,0

valuesを標準化

In [38]:
from sklearn.preprocessing import StandardScaler
stdsc = StandardScaler()
combined_std = stdsc.fit_transform(combined)

combinedを分割し、targetsを求める関数を定義

In [39]:
def recover_train_test_target():
    global combined
    
    train0 = pd.read_csv('../../トレーニングデータ+テストデータ/train.csv')
    
    targets = train0.Survived
    train = combined.ix[0:890]
    test = combined.ix[891:]
    
    return train,test,targets

In [40]:
train,test,targets = recover_train_test_target()

In [41]:
train

,PassengerId,Sex,Age,SibSp,Parch,Fare,Title_Master,Title_Miss,Title_Mr,Title_Mrs,...,Ticket_STONO2,Ticket_STONOQ,Ticket_SWPP,Ticket_WC,Ticket_WEP,Ticket_XXX,FamilySize,Singleton,SmallFamily,LargeFamily
0,1,1,22.0,1,0,7.2500,0,0,1,0,...,0,0,0,0,0,0,2,0,1,0
1,2,0,38.0,1,0,71.2833,0,0,0,1,...,0,0,0,0,0,0,2,0,1,0
2,3,0,26.0,0,0,7.9250,0,1,0,0,...,1,0,0,0,0,0,1,1,0,0
3,4,0,35.0,1,0,53.1000,0,0,0,1,...,0,0,0,0,0,1,2,0,1,0
4,5,1,35.0,0,0,8.0500,0,0,1,0,...,0,0,0,0,0,1,1,1,0,0
5,6,1,26.0,0,0,8.4583,0,0,1,0,...,0,0,0,0,0,1,1,1,0,0
6,7,1,54.0,0,0,51.8625,0,0,1,0,...,0,0,0,0,0,1,1,1,0,0
7,8,1,2.0,3,1,21.0750,1,0,0,0,...,0,0,0,0,0,1,5,0,0,1
8,9,0,27.0,0,2,11.1333,0,0,0,1,...,0,0,0,0,0,1,3,0,1,0
9,10,0,14.0,1,0,30.0708,0,0,0,1,...,0,0,0,0,0,1,2,0,1,0
10,11,0,4.0,1,1,16.7000,0,1,0,0,...,0,0,0,0,0,0,3,0,1,0
11,12,0,58.0,0,0,26.5500,0,1,0,0,...,0,0,0,0,0,1,1,1,0,0
12,13,1,20.0,0,0,8.0500,0,0,1,0,...,0,0,0,0,0,0,1,1,0,0
13,14,1,39.0,1,5,31.2750,0,0,1,0,...,0,0,0,0,0,1,7,0,0,1
14,15,0,14.0,0,0,7.8542,0,1,0,0,...,0,0,0,0,0,1,1,1,0,0
15,16,0,55.0,0,0,16.0000,0,0,0,1,...,0,0,0,0,0,1,1,1,0,0
16,17,1,2.0,4,1,29.1250,1,0,0,0,...,0,0,0,0,0,1,6,0,0,1
17,18,1,30.0,0,0,13.0000,0,0,1,0,...,0,0,0,0,0,1,1,1,0,0
18,19,0,31.0,1,0,18.0000,0,0,0,1,...,0,0,0,0,0,1,2,0,1,0
19,20,0,31.0,0,0,7.2250,0,0,0,1,...,0,0,0,0,0,1,1,1,0,0
20,21,1,35.0,0,0,26.0000,0,0,1,0,...,0,0,0,0,0,1,1,1,0,0
21,22,1,34.0,0,0,13.0000,0,0,1,0,...,0,0,0,0,0,1,1,1,0,0
22,23,0,15.0,0,0,8.0292,0,1,0,0,...,0,0,0,0,0,1,1,1,0,0
23,24,1,28.0,0,0,35.5000,0,0,1,0,...,0,0,0,0,0,1,1,1,0,0
24,25,0,8.0,3,1,21.0750,0,1,0,0,...,0,0,0,0,0,1,5,0,0,1
25,26,0,38.0,1,5,31.3875,0,0,0,1,...,0,0,0,0,0,1,7,0,0,1
26,27,1,26.0,0,0,7.2250,0,0,1,0,...,0,0,0,0,0,1,1,1,0,0
27,28,1,19.0,3,2,263.0000,0,0,1,0,...,0,0,0,0,0,1,6,0,0,1
28,29,0,18.0,0,0,7.8792,0,1,0,0,...,0,0,0,0,0,1,1,1,0,0
29,30,1,26.0,0,0,7.8958,0,0,1,0,...,0,0,0,0,0,1,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
861,862,1,21.0,1,0,11.5000,0,0,1,0,...,0,0,0,0,0,1,2,0,1,0
862,863,0,48.0,0,0,25.9292,0,0,0,1,...,0,0,0,0,0,1,1,1,0,0
863,864,0,18.0,8,2,69.5500,0,1,0,0,...,0,0,0,0,0,0,11,0,0,1
864,865,1,24.0,0,0,13.0000,0,0,1,0,...,0,0,0,0,0,1,1,1,0,0
865,866,0,42.0,0,0,13.0000,0,0,0,1,...,0,0,0,0,0,1,1,1,0,0
866,867,0,27.0,1,0,13.8583,0,1,0,0,...,0,0,0,0,0,0,2,0,1,0
867,868,1,31.0,0,0,50.4958,0,0,1,0,...,0,0,0,0,0,0,1,1,0,0
868,869,1,26.0,0,0,9.5000,0,0,1,0,...,0,0,0,0,0,1,1,1,0,0
869,870,1,4.0,1,1,11.1333,1,0,0,0,...,0,0,0,0,0,1,3,0,1,0
870,871,1,26.0,0,0,7.8958,0,0,1,0,...,0,0,0,0,0,1,1,1,0,0
871,872,0,47.0,1,1,52.5542,0,0,0,1,...,0,0,0,0,0,1,3,0,1,0
872,873,1,33.0,0,0,5.0000,0,0,1,0,...,0,0,0,0,0,1,1,1,0,0
873,874,1,47.0,0,0,9.0000,0,0,1,0,...,0,0,0,0,0,1,1,1,0,0
874,875,0,28.0,1,0,24.0000,0,0,0,1,...,0,0,0,0,0,0,2,0,1,0
875,876,0,15.0,0,0,7.2250,0,1,0,0,...,0,0,0,0,0,1,1,1,0,0
876,877,1,20.0,0,0,9.8458,0,0,1,0,...,0,0,0,0,0,1,1,1,0,0
877,878,1,19.0,0,0,7.8958,0,0,1,0,...,0,0,0,0,0,1,1,1,0,0
878,879,1,26.0,0,0,7.8958,0,0,1,0,...,0,0,0,0,0,1,1,1,0,0
879,880,0,56.0,0,1,83.1583,0,0,0,1,...,0,0,0,0,0,1,2,0,1,0
880,881,0,25.0,0,1,26.0000,0,0,0,1,...,0,0,0,0,0,1,2,0,1,0
881,882,1,33.0,0,0,7.8958,0,0,1,0,...,0,0,0,0,0,1,1,1,0,0
882,883,0,22.0,0,0,10.5167,0,1,0,0,...,0,0,0,0,0,1,1,1,0,0
883,884,1,28.0,0,0,10.5000,0,0,1,0,...,0,0,0,0,0,0,1,1,0,0
884,885,1,25.0,0,0,7.0500,0,0,1,0,...,0,0,0,0,0,0,1,1,0,0
885,886,0,39.0,0,5,29.1250,0,0,0,1,...,0,0,0,0,0,1,6,0,0,1
886,887,1,27.0,0,0,13.0000,0,0,0,0,...,0,0,0,0,0,1,1,1,0,0
887,888,0,19.0,0,0,30.0000,0,1,0,0,...,0,0,0,0,0,1,1,1,0,0
888,889,0,18.0,1,2,23.4500,0,1,0,0,...,0,0,0,1,0,0,4,0,1,0
889,890,1,26.0,0,0,30.0000,0,0,1,0,...,0,0,0,0,0,1,1,1,0,0
890,891,1,32.0,0,0,7.7500,0,0,1,0,...,0,0,0,0,0,1,1,1,0,0

ExtraTreesClassifierを用いて特徴量を削減

In [42]:
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.feature_selection import SelectFromModel
clf = ExtraTreesClassifier(n_estimators=200)
clf = clf.fit(train, targets)

In [43]:
features = pd.DataFrame()
features['feature'] = train.columns
features['importance'] = clf.feature_importances_

In [44]:
features.sort(['importance'],ascending=False)

//anaconda/envs/py35/lib/python3.5/site-packages/ipykernel/__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':

           feature  importance
0      PassengerId    0.127800
2              Age    0.118178
5             Fare    0.112203
1              Sex    0.112183
8         Title_Mr    0.106594
9        Title_Mrs    0.040021
7       Title_Miss    0.037407
26        Pclass_3    0.036672
23         Cabin_U    0.028697
24        Pclass_1    0.024144
66     SmallFamily    0.020413
64      FamilySize    0.019734
67     LargeFamily    0.019668
3            SibSp    0.017483
4            Parch    0.014816
25        Pclass_2    0.013644
6     Title_Master    0.013361
63      Ticket_XXX    0.012529
14      Embarked_S    0.011213
12      Embarked_C    0.010352
65       Singleton    0.010126
19         Cabin_E    0.010008
13      Embarked_Q    0.007687
10   Title_Officer    0.007157
16         Cabin_B    0.006822
41       Ticket_PC    0.006676
18         Cabin_D    0.006652
57    Ticket_STONO    0.006116
60     Ticket_SWPP    0.006108
17         Cabin_C    0.006023
..             ...         ...
20         Cabin_F    0.001695
21         Cabin_G    0.001361
11   Title_Royalty    0.001073
62      Ticket_WEP    0.000789
42       Ticket_PP    0.000762
36       Ticket_FC    0.000602
37      Ticket_FCC    0.000535
39     Ticket_LINE    0.000534
51      Ticket_SOC    0.000533
50  Ticket_SCParis    0.000472
49  Ticket_SCPARIS    0.000440
28       Ticket_A4    0.000418
22         Cabin_T    0.000310
47     Ticket_SCAH    0.000231
52      Ticket_SOP    0.000149
56       Ticket_SP    0.000126
43      Ticket_PPP    0.000081
54  Ticket_SOTONO2    0.000074
44       Ticket_SC    0.000060
38       Ticket_Fa    0.000058
46     Ticket_SCA4    0.000053
32       Ticket_AS    0.000049
48     Ticket_SCOW    0.000048
35  Ticket_CASOTON    0.000022
59   Ticket_STONOQ    0.000000
27        Ticket_A    0.000000
45     Ticket_SCA3    0.000000
30      Ticket_AQ3    0.000000
31      Ticket_AQ4    0.000000
40       Ticket_LP    0.000000

[68 rows x 2 columns]

SelectFromModelを用いて有用な特徴量のみ取り出す

In [45]:
model = SelectFromModel(clf, prefit=True)
all_train = model.transform(train)
all_train.shape

(891, 15)

In [46]:
real_test = model.transform(test)
real_test.shape

(418, 15)

all_trainをX_train, y_train,に分割し、targetsからX_test_1tとy_test_1を作成

In [47]:
from sklearn.cross_validation import train_test_split
X_train, X_test_1, y_train, y_test_1 = train_test_split(all_train, targets.values, test_size=0.33, random_state=0)

X_trainをX_train_1,X_train_2に分割し、y_trainからy_train_1,y_train_2

In [48]:
X_train_1, X_train_2, y_train_1, y_train_2 = train_test_split(X_train, y_train, test_size=0.5, random_state=0)

In [49]:
np.save('../data/X_train_1.npy', X_train_1)
np.save('../data/y_train_1.npy', y_train_1)
np.save('../data/X_train_2.npy', X_train_2)
np.save('../data/y_train_2.npy', y_train_2)
np.save('../data/X_test_1.npy', X_test_1)
np.save('../data/y_test_1.npy', y_test_1)